# Ćwiczenie 9

Przed wykonaniem ćwiczenia należy zapoznać się z rozdziałem 6 i 8 opisującym formy prezentacji wyników badań, w tym tworzenie prezentacji multimedialnych. 

## Cel ćwiczenia

Celem ćwiczenia jest zapoznanie się z formą prezentacji wyników badań w postaci prezentacji multimedialnej oraz opracowanie prezentacji multimedialnej przedstawiającej analizę zmian przetrzennego rozkładu rasowo-etnicznej struktury ludności oraz zróżnicowania rasowo-etnicznego w hrabstwie w latach 1990-2020.

## Wykorzystane dane

W ćwiczeniu zostaną wykorzystane wyniki analiz opracowanych w ramach ćwiczenia 6,7 i 8.

## Zadanie

-   Każda grupa przygotowuje 10 minutową prezentację multimedialną przedstawiającą wyniki zmian przetrzennego rozkładu rasowo-etnicznej struktury ludności oraz zróżnicowania rasowo-etnicznego w hrabstwie w latach 1990-2020.

-   Przygotowana prezentacja powinna składać się z maksymalnie 10-12 slajdów.

-   Ważnym elementem przygotowania prezentacji jest odpowiednia selekcja materiału oraz odpowiedni dobór wizualizacji do formy prezentacji.
